site_name: uringio
site_url: https://AivazianArtur.github.io/uringio/
site_description: High-performance io_uring wrapper for Python
repo_url: https://github.com/AivazianArtur/uringio
edit_uri: ''

docs_dir: docs_site
site_dir: site

theme:
  name: material
  features:
    - navigation.sections
    - navigation.tabs
    - toc.integrate
    - content.code.copy
  palette:
    scheme: slate

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

nav:
  - Home: index.md
  - User Guide: user-guide.md
  - Shortly about io_uring: io-uring.md
  - Development: development.md
  - Architecture: architecture.md
  - Benchmark analysis: benchmarks-analysis.md
  - API Reference:
      - Overview: api.md
      - UringioLoop: api/loop.md
      - File: api/file.md
      - Socket: api/socket.md
      - Context Managers: api/context-managers.md
      - Enums: api/enums.md
      - Module Functions: api/module-functions.md
  - PyPI: https://pypi.org/project/uringio/
