[build-system]
requires = ["setuptools>=72,<81", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "uringio"
version = "0.4.4"
requires-python = ">=3.12"
authors = [
  {name = "Aivazian Artur", email = "arcanwork@gmail.com"},
  {email = "aivazian.artur.artakovich@gmail.com"},
]
maintainers = [
  {name = "Aivazian Artur", email = "arcanwork@gmail.com"}
]
description = "High-Performance io_uring wrapper for Python"
readme = {file = "README.md", content-type = "text/markdown"}
license = {file = "LICENSE"}

[project.urls]
Homepage = "https://aivazianartur.github.io/uringio/"
Documentation = "https://aivazianartur.github.io/uringio/"
Repository = "https://github.com/AivazianArtur/uringio.git"
Issues = "https://github.com/AivazianArtur/uringio/issues"
Changelog = "https://github.com/AivazianArtur/uringio/blob/main/CHANGELOG.md"

[tool.setuptools]
packages = ["uringio_stubs"]

[tool.setuptools.package-data]
"uringio_stubs" = ["py.typed", "*.pyi"]

[tool.cibuildwheel]
build = "cp312-* cp313-* cp314-*"
skip = "*-musllinux_*"


test-command = "python -c \"import uringio\""
